package edu.eci.cvds.auth.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a user in the system.
 * <p>
 * This entity is mapped to the "users" collection in MongoDB and contains basic user information such as
 * name, email, password, and role.
 */
@Document("users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * The unique identifier of the user.
     * <p>
     * This ID is generated by MongoDB and is used to uniquely identify the user in the database.
     */
    @Id
    private String id;
    private String name;
    private String email;
    private String password;
    private Role role;
}